apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deployer

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      manifest:
        type: string
        required: true

jobs:
  hackers-api:
    if: ${{ fromJSON(inputs.manifest)['fidelity-api']['hackers-api'].deploy }}
    steps:
      - name: Simulate hackers-api deployment
        run: |
          echo "Component: hackers-api"
          echo "Environment: ${{ inputs.environment }}"
          echo "Artifact ID: ${{ fromJSON(inputs.manifest)['fidelity-api']['hackers-api'].id }}"
          echo "Artifact URL: ${{ fromJSON(inputs.manifest)['fidelity-api']['hackers-api'].url }}"
          echo
          echo "Simulating deployment..."
          sleep 5
          echo
          echo "Deployment completed successfully."

  hackers-auth:
    if: ${{ fromJSON(inputs.manifest)['fidelity-auth']['hackers-auth'].deploy }}
    steps:
      - name: Simulate hackers-auth deployment
        run: |
          echo "Component: hackers-auth"
          echo "Environment: ${{ inputs.environment }}"
          echo "Artifact ID: ${{ fromJSON(inputs.manifest)['fidelity-auth']['hackers-auth'].id }}"
          echo "Artifact URL: ${{ fromJSON(inputs.manifest)['fidelity-auth']['hackers-auth'].url }}"
          echo
          echo "Simulating deployment..."
          sleep 5
          echo
          echo "Deployment completed successfully."

  hackers-web:
    if: ${{ fromJSON(inputs.manifest)['fidelity-web']['hackers-web'].deploy }}
    steps:
      - name: Simulate hackers-web deployment
        run: |
          echo "Component: hackers-web"
          echo "Environment: ${{ inputs.environment }}"
          echo "Artifact ID: ${{ fromJSON(inputs.manifest)['fidelity-web']['hackers-web'].id }}"
          echo "Artifact URL: ${{ fromJSON(inputs.manifest)['fidelity-web']['hackers-web'].url }}"
          echo
          echo "Simulating deployment..."
          sleep 5
          echo
          echo "Deployment completed successfully."